services:
  app:
    build:
      context: ..
      dockerfile: dockerfiles/Dockerfile.flask
    ports:
      - "5001:5000"
    volumes:
      - /data/servisplus_dev/database.db:/app/app/database/database.db
      - /data/servisplus_dev/videos:/app/app/videos
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000"]
      interval: 30s
      timeout: 10s
      retries: 3

  nginx:
    image: nginx:1.24.0
    ports:
      - "83:80"
      - "10443:443"
    volumes:
      - ../configs/default-dev.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - app
    restart: unless-stopped
