name: automatic PR

on:
 push:
  branches:
   - develop

jobs:
 updateAuthor:
  runs-on: ubuntu-latest

  steps:
   - name: checkout
     uses: actions/checkout@v2

   - name: extract git commit data
     uses: rlespinasse/git-commit-data-action@v1.x

   - name: update author info
     run: echo ${{ env.GIT_COMMIT_AUTHOR_NAME }} > AUTHOR

   - name: create PR
     uses: peter-evans/create-pull-request@v4
     with:
      branch: develop
      base: master
      committer: ${{ env.GIT_COMMIT_AUTHOR_NAME }} <${{ env.GIT_COMMIT_AUTHOR_EMAIL }}>
      author: ${{ env.GIT_COMMIT_AUTHOR_NAME }} <${{ env.GIT_COMMIT_AUTHOR_EMAIL }}>
      token: ${{ secrets.GITHUB_TOKEN }}
      commit-message: "merge: develop into master"
      body: "Automatic PR from develop to master"
